# typings/lgpio/__init__.pyi
from typing import Callable

RISING_EDGE: int
FALLING_EDGE: int
BOTH_EDGES: int

def gpiochip_open(chip: int) -> int: ...
def gpiochip_close(handle: int) -> None: ...
def gpio_claim_input(handle: int, gpio: int, flags: int = ...) -> None: ...
def gpio_claim_alert(
    handle: int, gpio: int, edge: int, flags: int = ..., infra: int = ...
) -> None: ...
def callback(
    handle: int, gpio: int, edge: int, func: Callable[[int, int, int, int], None]
) -> object: ...
